Repository Agents4Good/YUMA, pull requests merged in 2025-04, with the labels that each got.

#49 feat: cria script para testes
  src/scripts/joke_generator.py
Labels: enhancement

#55 Correção do CLI do Arquiteto
  src/main.py
Labels: bug, fix

#56 Feat: Dicionário Python com o YAML no State
  src/agents.py
  src/main.py
  src/scripts/joke_generator.py
  src/state.py
  src/tools.py
Labels: enhancement, fix, refact

#58 Feat: adicionado geração da imagem do sub-grafo
  .gitignore
  generated_files/.gitkeep
  src/agents.py
  src/main.py
  src/utils/io_functions.py
Labels: enhancement

#61 Feat/tools logic nodes
  src/agents.py
  src/prompts/agents_prompts.py
  src/scripts/avalia_notas.py
  src/scripts/if_else_test.py
  src/tools.py
  src/utils/tools_utils.py
Labels: enhancement, fix, refact

#69 Adiciona integração com DeepInfra
  .env-example
  requirements.txt
  src/agents.py
Labels: enhancement

#59 Feat/documentacao
  README.md
  docs/README.md
  docs/dev/agents/architecture.md
  docs/dev/agents/dify/edge_creator.md
  docs/dev/agents/dify/node_creator.md
  docs/dev/agents/dify/supervisor.md
  docs/dev/agents/requirements_engineer.md
  docs/dev/arquitetura.md
  docs/dev/tools/dify/create_answer_node.md
  docs/dev/tools/dify/create_edges.md
  docs/dev/tools/dify/create_llm_node.md
  docs/dev/tools/dify/create_metadata.md
  docs/dev/tools/dify/create_start_node.md
  docs/dev/tools/make_handoff.md
  docs/dev/tools/sequence_diagram_generator.md
  docs/dev/workflow/main.md
  docs/guias/exemplos.md
Labels: documentation

#75 Refatorações e fixes resolvendo a integração do novo modelo com o sistema
  .env-example
  .env.example
  requirements.txt
  src/agents.py
  src/prompts/agents_prompts.py
  src/tools.py
  src/utils/tools_utils.py
Labels: bug, fix, refact

#79 fix: conserta execução dos scripts
  src/scripts/avalia_notas.py
  src/scripts/if_else_test.py
  src/scripts/joke_generator.py
Labels: bug

#89 feat/fix: variável de contexto no campo errado
  src/tools/dify/ai_tools.py
Labels: fix, refact

#85 Modularização da arquitetura do sistema e refatorações gerais
  .gitignore
  src/agents.py
  src/agentshub/dify/__init__.py
  src/agentshub/dify/edge_creator/__init__.py
  src/agentshub/dify/edge_creator/edge_creator.py
  src/agentshub/dify/edge_creator/prompt.py
  src/agentshub/dify/node_creator/__init__.py
  src/agentshub/dify/node_creator/node_creator.py
  src/agentshub/dify/node_creator/prompt.py
  src/agentshub/dify/supervisor/__init__.py
  src/agentshub/dify/supervisor/supervisor.py
  src/agentshub/genia/__init__.py
  src/agentshub/genia/architect/__init__.py
  src/agentshub/genia/architect/architect.py
  src/agentshub/genia/architect/prompt.py
  src/agentshub/genia/architect/structured_output.py
  src/agentshub/genia/architect/utils.py
  src/agentshub/genia/human_node/__init__.py
  src/agentshub/genia/human_node/human_node.py
  src/agentshub/genia/requirements_engineer/__init__.py
  src/agentshub/genia/requirements_engineer/prompt.py
  src/agentshub/genia/requirements_engineer/requirements_engineer.py
  src/main.py
  src/models/__init__.py
  src/models/dify/__init__.py
  src/models/dify/models.py
  src/models/genia/__init__.py
  src/models/genia/models.py
  src/models/models.py
  src/prompts/agents_prompts.py
  src/schema/dify/__init__.py
  src/schema/dify/state.py
  src/schema/genia/__init__.py
  src/schema/genia/state.py
  src/scripts/avalia_notas.py
  src/scripts/if_else_test.py
  src/scripts/joke_generator.py
  src/state.py
  src/tools/__init__.py
  src/tools/dify/__init__.py
  src/tools/dify/ai_tools.py
  src/tools/dify/edge_tools.py
  src/tools/dify/entry_exit_tools.py
  src/tools/dify/logic_tools.py
  src/tools/dify/utils.py
  src/tools/dify/web_tools.py
  src/tools/genia/__init__.py
  src/tools/genia/utils.py
  src/utils/dify/__init__.py
  src/utils/dify/dify_gateway.py
  src/utils/dify/nodes.py
  src/utils/genia/__init__.py
  src/utils/genia/io_functions.py
  src/utils/genia/plantuml_parser.py
Labels: enhancement, fix, refact
