Repository Agents4Good/YUMA, pull requests merged in 2025-05, with the labels that each got.

#90 fix: modelo no env.example
  .env.example
Labels: fix

#92 Criação do nó Agente com tool de busca na web com Tavily Search
  src/agentshub/dify/node_creator/prompt.py
  src/agentshub/genia/architect/architect.py
  src/agentshub/genia/architect/prompt.py
  src/tools/dify/__init__.py
  src/tools/dify/ai_tools.py
  src/tools/dify/entry_exit_tools.py
  src/tools/dify/utils.py
  src/utils/dify/nodes.py
Labels: enhancement

#96 Refact: Separação do Node Creator
  src/agentshub/__init__.py
  src/agentshub/base_agents.py
  src/agentshub/dify/__init__.py
  src/agentshub/dify/edge_creator/prompt.py
  src/agentshub/dify/node_creation/__init__.py
  src/agentshub/dify/node_creation/agent_node_creator/__init__.py
  src/agentshub/dify/node_creation/agent_node_creator/agent_node_creator.py
  src/agentshub/dify/node_creation/agent_node_creator/prompt.py
  src/agentshub/dify/node_creation/answer_node_creator/__init__.py
  src/agentshub/dify/node_creation/answer_node_creator/answer_node_creator.py
  src/agentshub/dify/node_creation/answer_node_creator/prompt.py
  src/agentshub/dify/node_creation/http_node_creator/__init__.py
  src/agentshub/dify/node_creation/http_node_creator/http_node_creator.py
  src/agentshub/dify/node_creation/http_node_creator/prompt.py
  src/agentshub/dify/node_creation/llm_node_creator/__init__.py
  src/agentshub/dify/node_creation/llm_node_creator/llm_node_creator.py
  src/agentshub/dify/node_creation/llm_node_creator/prompt.py
  src/agentshub/dify/node_creation/logic_node_creator/__init__.py
  src/agentshub/dify/node_creation/logic_node_creator/logic_node_creator.py
  src/agentshub/dify/node_creation/logic_node_creator/prompt.py
  src/agentshub/dify/node_creation/start_node_creator/__init__.py
  src/agentshub/dify/node_creation/start_node_creator/prompt.py
  src/agentshub/dify/node_creation/start_node_creator/start_node_creator.py
  src/agentshub/dify/node_creator/__init__.py
  src/agentshub/dify/node_creator/node_creator.py
  src/agentshub/dify/node_creator/prompt.py
  src/agentshub/dify/supervisor/__init__.py
  src/agentshub/dify/supervisor/prompt.py
  src/agentshub/dify/supervisor/structured_output.py
  src/agentshub/dify/supervisor/supervisor.py
  src/agentshub/genia/architect/architect.py
  src/main.py
  src/models/__init__.py
  src/models/dify/__init__.py
  src/models/dify/models.py
  src/models/genia/__init__.py
  src/models/genia/models.py
  src/models/models.py
  src/schema/genia/__init__.py
  src/utils/__init__.py
  src/utils/dify/nodes.py
  src/utils/extract_tools.py
  src/utils/genia/__init__.py
  src/utils/json_utils.py
Labels: refact

#102 Estilização do sistema via terminal
  requirements.txt
  src/main.py
  src/utils/genia/__init__.py
  src/utils/genia/io_functions.py
Labels: enhancement, refact

#112 Criação de arquivos de log
  generated_files/logs/.gitkeep
  src/agentshub/dify/edge_creator/edge_creator.py
  src/agentshub/dify/node_creation/agent_node_creator/agent_node_creator.py
  src/agentshub/dify/node_creation/answer_node_creator/answer_node_creator.py
  src/agentshub/dify/node_creation/http_node_creator/http_node_creator.py
  src/agentshub/dify/node_creation/llm_node_creator/llm_node_creator.py
  src/agentshub/dify/node_creation/logic_node_creator/logic_node_creator.py
  src/agentshub/dify/node_creation/start_node_creator/start_node_creator.py
  src/agentshub/dify/supervisor/supervisor.py
  src/agentshub/genia/architect/architect.py
  src/agentshub/genia/human_node/human_node.py
  src/agentshub/genia/requirements_engineer/requirements_engineer.py
  src/main.py
  src/models/models.py
  src/scripts/avalia_notas.py
  src/scripts/if_else_test.py
  src/scripts/joke_generator.py
  src/tools/dify/ai_tools.py
  src/tools/dify/edge_tools.py
  src/tools/dify/entry_exit_tools.py
  src/tools/dify/logic_tools.py
  src/tools/dify/web_tools.py
  src/utils/dify/nodes.py
  src/utils/extract_tools.py
  src/utils/genia/__init__.py
  src/utils/genia/io_functions.py
  src/utils/genia/log_functions.py
  src/utils/json_utils.py
Labels: enhancement

#111 Feat: Few-Shot
  src/agentshub/base_agents.py
  src/agentshub/dify/edge_creator/edge_creator.py
  src/agentshub/dify/node_creation/agent_node_creator/agent_node_creator.py
  src/agentshub/dify/node_creation/agent_node_creator/examples.py
  src/agentshub/dify/node_creation/answer_node_creator/answer_node_creator.py
  src/agentshub/dify/node_creation/answer_node_creator/examples.py
  src/agentshub/dify/node_creation/http_node_creator/examples.py
  src/agentshub/dify/node_creation/http_node_creator/http_node_creator.py
  src/agentshub/dify/node_creation/llm_node_creator/examples.py
  src/agentshub/dify/node_creation/llm_node_creator/llm_node_creator.py
  src/agentshub/dify/node_creation/logic_node_creator/examples.py
  src/agentshub/dify/node_creation/logic_node_creator/logic_node_creator.py
  src/agentshub/dify/node_creation/start_node_creator/examples.py
  src/agentshub/dify/node_creation/start_node_creator/start_node_creator.py
  src/agentshub/dify/supervisor/supervisor.py
  src/agentshub/genia/architect/__init__.py
  src/agentshub/genia/architect/prompt.py
  src/agentshub/genia/architect/structured_output.py
  src/utils/dify/__init__.py
  src/utils/dify/build_few_shot.py
  src/utils/dify/nodes.py
  src/utils/genia/io_functions.py
  src/utils/genia/log_functions.py
  src/utils/genia/plantuml_parser.py
  src/utils/genia/print_functions.py
Labels: enhancement

#110 Feat/retry
  src/agentshub/base_agents.py
  src/agentshub/genia/architect/architect.py
  src/agentshub/genia/requirements_engineer/requirements_engineer.py
  src/tools/genia/utils.py
  src/utils/genia/plantuml_parser.py
Labels: enhancement
