Repository Agents4Good/YUMA, pull requests merged in 2025-03, with the labels that each got.

#15 Agente analisador de requisitos
  src/agents.py
  src/main.py
Labels: bug, enhancement

#17 Feat: agente gerador de arquitetura
  src/agents.py
  src/main.py
  src/outputs.py
  src/state.py
  src/tools.py
Labels: enhancement

#21 Feat/sequence diagram
  .gitignore
  requirements.txt
  src/agents.py
  src/tools.py
  src/utils/plantuml_parser.py
Labels: enhancement

#27 Feat/dify supervisor
  .gitignore
  src/agents.py
  src/prompts/agents_prompts.py
  src/state.py
Labels: enhancement

#28 Tools de serialização e suporte a multi LLMs no YAML
  docs/dev/.gitkeep
  src/tools.py
  src/utils/tools_utils.py
  test_mod.yml
Labels: enhancement

#29 Feat: Agente criador nós
  .gitignore
  src/agents.py
  src/main.py
  src/prompts/agents_prompts.py
  src/tools.py
Labels: enhancement

#35 Refact/prompts diagram files
  .gitignore
  generated_files/.gitkeep
  src/agents.py
  src/main.py
  src/outputs.py
  src/prompts/agents_prompts.py
  src/tools.py
  src/utils/io_functions.py
  src/utils/plantuml_parser.py
Labels: refact

#39 Revert "Refact/prompts diagram files"
  .gitignore
  generated_files/.gitkeep
  src/agents.py
  src/main.py
  src/outputs.py
  src/prompts/agents_prompts.py
  src/tools.py
  src/utils/io_functions.py
  src/utils/plantuml_parser.py
Labels: fix

#44 Feat / Criação de edges no Dify
  src/agents.py
  src/prompts/agents_prompts.py
  src/tools.py
Labels: enhancement
